### ISSUE TITLE
android : Experienced exception processing API response. Failing task.

### ISSUE THREAD

**Issue by chintansoni202** [Appboy/appboy-unity-sdk#32]
I am not able to log custom events. I am getting below error log, irrespective of any Android OS version.

```
W/Appboy v2.2.1 .bo.app.cr: Experienced exception processing API response. Failing task.
                                                                                          bo.app.ar: Bad Http response code from Appboy: [503]
                                                                                              at bo.app.c.a(SourceFile:118)
                                                                                              at bo.app.c.a(SourceFile:78)
                                                                                              at bo.app.c.a(SourceFile:57)
                                                                                              at bo.app.c.a(SourceFile:48)
                                                                                              at bo.app.h.a(SourceFile:36)
                                                                                              at bo.app.f.a(SourceFile:34)
                                                                                              at bo.app.cr.a(SourceFile:88)
                                                                                              at bo.app.cr.run(SourceFile:61)
                                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                              at java.lang.Thread.run(Thread.java:764)
```

I am using latest SDK version `2.2.1`.

Am I remaining with any steps to follow ?

**Comment by Bucimis** [comment]
Hi @chintansoni202,

Thanks for filing an issue with us. We're investigating with the server team.

In the meantime, a few followup questions:
1) Are you seeing failures only when you log custom events, or are all API calls failing regardless of content?
2) Have you double checked your server endpoint and Braze API key?
3) Did you begin experiencing this issue this morning, or have you never been able to successfully send custom events to the Braze backend?

Thanks,
Braze SDK Engineering

**Comment by Bucimis** [comment]
@chintansoni202 were you able to resolve this issue?

**Comment by Bucimis** [comment]
@chintansoni202 closing for now, please re-open if you encounter again.
