### ISSUE TITLE
In-App Messages on Android

### ISSUE THREAD

**Issue by TagGamesJames** [Appboy/appboy-unity-sdk#47]
While trying to update Braze we've encountered a crash every version up from (and including) 1.17.0 when trying to display In-App Messages on Android devices that have SDK levels below that of 28. Below is the log that appears with one of those devices.

    `java.lang.Error: FATAL EXCEPTION [main]
    Unity version     : 2018.1.2f1
    Device model      : samsung SM-G900F
    Device fingerprint: samsung/kltexx/klte:5.0/LRX21T/G900FXXU1BOJ1:user/release-keys
    
    Caused by: java.lang.NoSuchMethodError: No virtual method getDisplayCutout()Landroid/support/v4/view/DisplayCutoutCompat; in class Landroid/support/v4/view/WindowInsetsCompat; or its super classes (declaration of 'android.support.v4.view.WindowInsetsCompat' appears in /data/app/*package_name*/base.apk)
        at com.appboy.ui.inappmessage.InAppMessageViewWrapper$2.onApplyWindowInsets(InAppMessageViewWrapper.java:167)
        at android.support.v4.view.ViewCompat$ViewCompatApi21Impl$1.onApplyWindowInsets(ViewCompat.java:1307)
        at android.view.View.dispatchApplyWindowInsets(View.java:6944)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:6121)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:6125)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:6125)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchApplyWindowInsets(PhoneWindow.java:2573)
        at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:1334)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1588)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6558)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
        at android.view.Choreographer.doCallbacks(Choreographer.java:590)
        at android.view.Choreographer.doFrame(Choreographer.java:560)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5832)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)`

**Comment by radixdev** [comment]
That SDK version requires version 28 of the v4 support library. What version of the support library are you using in your app?

**Comment by TagGamesJames** [comment]
We had version 27 installed. Will update that now, thank you very much for the quick reply.
Just for future reference, is this mentioned anywhere in the SDK set up documentation? Couldn't find it on the Unity -> Android, or Android sections themselves.

**Comment by radixdev** [comment]
We have that information listed in https://github.com/Appboy/appboy-android-sdk#version-support. From multiple sources however, it appears that section isn't very visible. Do you have a recommendation of where you'd additionally like to see that information?

**Comment by TagGamesJames** [comment]
I think it would be more visually accessible if it was included in the developer documentation, specifically the platform integration guides. (https://www.braze.com/docs/developer_guide/platform_integration_guides/unity/android/sdk_integration/)

**Comment by radixdev** [comment]
Thanks @TagGamesJames , we'll see about adding that to our docs.
