### ISSUE TITLE
[Bug]: Android App Crashes With java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/CoroutineScope

### ISSUE THREAD

**Issue by starikcetin** [Appboy/appboy-unity-sdk#97]
### Braze Unity SDK Version

3.8.1

### Steps To Reproduce

Build a Unity Project for the Android platform that has Braze Unity SDK 3.8.1 and [External Dependency Manager](https://github.com/googlesamples/unity-jar-resolver) installed. Launch the app. It crashes immediately and prints this in the logcat:

```
07-28 11:42:02.386 14085 14085 E AndroidRuntime: FATAL EXCEPTION: main
07-28 11:42:02.386 14085 14085 E AndroidRuntime: Process: <snip for privacy>, PID: 14085
07-28 11:42:02.386 14085 14085 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/CoroutineScope;
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at com.appboy.Appboy.<init>(SourceFile:74)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at com.braze.Braze.<init>(SourceFile:1)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at com.appboy.Appboy.getInstance(SourceFile:4)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at com.braze.Braze.getInstance(SourceFile:1)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at com.appboy.unity.BrazeUnityActivityWrapper.onCreateCalled(BrazeUnityActivityWrapper.kt:34)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at com.appboy.unity.AppboyUnityPlayerActivity.onCreate(AppboyUnityPlayerActivity.kt:21)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8142)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8114)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3537)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3736)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8031)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
07-28 11:42:02.386 14085 14085 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.CoroutineScope
07-28 11:42:02.386 14085 14085 E AndroidRuntime: 	... 21 more
```

### Expected Behavior

I expected my app to not crash.

### Actual Incorrect Behavior

My app crashed.

### Additional Information

I believe there is a missing dependency listing in the 3.8.1 SDK. Is suspect it to be `org.jetbrains.kotlinx:kotlinx-coroutines-core`.

**Comment by starikcetin** [comment]
Please disregard.

**Comment by radixdev** [comment]
Please follow https://www.braze.com/docs/developer_guide/platform_integration_guides/unity/sdk_integration/android/#unity-android-gradle-configuration to add Kotlin coroutines to your app.
